FROM debian:sid

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       bash \
       ca-certificates \
       emacs-gtk \
       git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /repo
CMD ["bash"]
